name: AWS Deployment
on:
  push:
    branches:
      - master 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"
      - run: docker build -t omaramsoul/aws-deployment -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true omaramsoul/aws-deployment npm test
      # build our images
      - run: docker build -t omaramsoul/multi-client-10-14 ./client
      - run: docker build -t omaramsoul/multi-nginx-10-14 ./nginx
      - run: docker build -t omaramsoul/multi-server-10-14 ./server
      - run: docker build -t omaramsoul/multi-worker-10-14 ./worker
      # push those images to docker hub
      - run: docker push omaramsoul/multi-client-10-14
      - run: docker push omaramsoul/multi-nginx-10-14
      - run: docker push omaramsoul/multi-server-10-14
      - run: docker push omaramsoul/multi-worker-10-14

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: "${{ secrets.AWS_SECRET_KEY }}"
          application_name: aws-deployment
          environment_name: Aws-deployment-env
          existing_bucket_name: elasticbeanstalk-us-east-1-656885045458
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip